#!/usr/bin/env bash
set -euo pipefail

while true; do
    read -r -p "Are you running this script from the /cc-admin directory? [y/n] " input
    case $input in
        [yY][eE][sS]|[yY])
            break
            ;;
        [nN][oO]|[nN])
            echo "pls come again."
            exit 0
            ;;
        *)
            echo "Please answer yes or no."
            ;;
    esac
done

export PATH="$PATH:$PWD/scripts"
export CCA_BLD="$PWD/builds"
export CCA_SRC=$PWD

VERSION=$(pm g version)
VERSION=$(sed -e 's/^"//' -e 's/"$//' <<<"$VERSION")
NAME=$(pm g name)
NAME=$(sed -e 's/^"//' -e 's/"$//' <<<"$NAME")

export CCA_DEST="$PWD/../staging/v$VERSION"

echo "Development build of $NAME at v$VERSION"

printf 'Packing %s version %s...\n' "$NAME" "$VERSION"
cd "$CCA_BLD"
# printf 'npm pack %s\n' "$CCA_SRC"
npm pack "$CCA_SRC"


printf 'Installing cc-admin npm package into %s\n' "$CCA_DEST"
while true; do
    read -r -p "Proceed? [y/n] " input
    case $input in
        [yY][eE][sS]|[yY])
            if [ ! -f "$CCA_DEST" ]
            then
                mkdir "$CCA_DEST"
            fi

            cd "$CCA_DEST"
            # printf 'npm install %s/%s-%s.tgz\n' "$CCA_SRC" "$NAME" "$VERSION"
            npm install "$CCA_BLD/$NAME-$VERSION.tgz"
            break
            ;;
        [nN][oO]|[nN])
            echo "pls come again."
            exit 0
            ;;
        *)
            echo "Please answer yes or no."
            ;;
    esac
done
