#!/usr/bin/env bash
set -euo pipefail
die() {
    printf '%s\n' "$1" >&2
    exit 1
}

set_build_vars() {
    # setup directory path variables
    export _conf="/project.json"
    echo "what is in a $name"
    # load in source directories
    export _src=$($jq -r .paths."$name".src.root "$cca$_conf")
    export _dest=$($jq -r .paths."$name".dest.root "$cca$_conf")
}

unset_build_vars() {
    # setup directory path variables
    unset _conf

    # load in source directories
    unset _src
    unset _dest
}

export set_build_vars
export unset_build_vars
